### ISSUE TITLE
Console.WriteLine(object) hook is incorrectly written.

### ISSUE THREAD

**Issue by kevzhao2** [DeathCradle/Open-Terraria-API#17]
As you can see here, `Arg1` is being initialized instead of `Format`.

https://github.com/DeathCradle/Open-Terraria-API/blob/9d027c9a306449d3cdb08fba5366860bf0b2130c/OTAPI.Modifications/OTAPI.Modifications.Console/Callbacks/WriteLine.cs#L34-L39

**Comment by DeathCradle** [comment]
i think that was intentional laziness at the time as it handled non-string arguments when replacing all references in the terraria assembly (ie if an exception or bool was on the stack when calling WriteLine), and of course Format is a string and i didn't wan't OTAPI trying to format those objects itself, so it was better to leave that to the consumer. 
that said im open to PR's if you want to have something decent here, i dont think these hooks are used much at all though.
